name: CI/CD

on:
  push:
    paths:
      - '.github/workflows/ci-cd.yml'

env:
  TAG: master
  USER: Mikk155
  REPOSITORY: halflife-updated

jobs:
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --upgrade pip

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86

      - name: Build
        run: msbuild projects/vs2019/projects.sln -t:rebuild -property:Configuration=Release -maxcpucount:2

      - name: Deploy Win32
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TAG: ${{ env.TAG }}
          USER: ${{ env.USER }}
          REPOSITORY: ${{ env.REPOSITORY }}
        run: python3 build.py
